main:
  - name: Syllabus
    url: /syllabus/
    weight: 1
  - name: Schedule
    url: /schedule/
    weight: 2
  - name: Readings
    url: /reading/
    weight: 3
  - name: Assignments
    url: /assignment/
    weight: 4
  - name: Classes
    url: /class/
    weight: 5
  - name: Reference
    url: /reference/
    weight: 6
assignment:
  - name: Assignments
    weight: 1
  - name: Problem sets
    weight: 2
  - name: Evaluation
    weight: 3
  - name: Other projects
    weight: 4
